package ec.edu.ups.canchas.objetos;
// Generated 09-feb-2016 21:36:26 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Canchas generated by hbm2java
 */
@Entity
@Table(name = "canchas", catalog = "canchas")
public class Canchas implements java.io.Serializable {

	private Integer idcanchas;
	private Complejo complejo;
	private Integer capacidad;
	private Integer numero;
	private Set<Reservas> reservases = new HashSet<Reservas>(0);

	public Canchas() {
	}

	public Canchas(Complejo complejo) {
		this.complejo = complejo;
	}

	public Canchas(Complejo complejo, Integer capacidad, Integer numero, Set<Reservas> reservases) {
		this.complejo = complejo;
		this.capacidad = capacidad;
		this.numero = numero;
		this.reservases = reservases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcanchas", unique = true, nullable = false)
	public Integer getIdcanchas() {
		return this.idcanchas;
	}

	public void setIdcanchas(Integer idcanchas) {
		this.idcanchas = idcanchas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "complejo_idcomplejo", nullable = false)
	public Complejo getComplejo() {
		return this.complejo;
	}

	public void setComplejo(Complejo complejo) {
		this.complejo = complejo;
	}

	@Column(name = "capacidad")
	public Integer getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(Integer capacidad) {
		this.capacidad = capacidad;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canchas")
	public Set<Reservas> getReservases() {
		return this.reservases;
	}

	public void setReservases(Set<Reservas> reservases) {
		this.reservases = reservases;
	}

}
