package ec.edu.ups.canchas.objetos;
// Generated 09-feb-2016 21:36:26 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Complejo generated by hbm2java
 */
@Entity
@Table(name = "complejo", catalog = "canchas")
public class Complejo implements java.io.Serializable {

	private int idcomplejo;
	private Usuario usuario;
	private String nombreComercial;
	private String razonSocial;
	private String ruc;
	private String coordenadasx;
	private String coordenadasy;
	private String direccion;
	private String email;
	private Date horaApertura;
	private Date horaCierre;
	private String ciudad;
	private BigDecimal costoHora;
	private Set<Canchas> canchases = new HashSet<Canchas>(0);
	private Set<Telefonos> telefonoses = new HashSet<Telefonos>(0);

	public Complejo() {
	}

	public Complejo(int idcomplejo, Usuario usuario, String nombreComercial, String razonSocial) {
		this.idcomplejo = idcomplejo;
		this.usuario = usuario;
		this.nombreComercial = nombreComercial;
		this.razonSocial = razonSocial;
	}

	public Complejo(int idcomplejo, Usuario usuario, String nombreComercial, String razonSocial, String ruc,
			String coordenadasx, String coordenadasy, String direccion, String email, Date horaApertura,
			Date horaCierre, String ciudad, BigDecimal costoHora, Set<Canchas> canchases, Set<Telefonos> telefonoses) {
		this.idcomplejo = idcomplejo;
		this.usuario = usuario;
		this.nombreComercial = nombreComercial;
		this.razonSocial = razonSocial;
		this.ruc = ruc;
		this.coordenadasx = coordenadasx;
		this.coordenadasy = coordenadasy;
		this.direccion = direccion;
		this.email = email;
		this.horaApertura = horaApertura;
		this.horaCierre = horaCierre;
		this.ciudad = ciudad;
		this.costoHora = costoHora;
		this.canchases = canchases;
		this.telefonoses = telefonoses;
	}

	@Id

	@Column(name = "idcomplejo", unique = true, nullable = false)
	public int getIdcomplejo() {
		return this.idcomplejo;
	}

	public void setIdcomplejo(int idcomplejo) {
		this.idcomplejo = idcomplejo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre_comercial", nullable = false, length = 250)
	public String getNombreComercial() {
		return this.nombreComercial;
	}

	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}

	@Column(name = "razon_social", nullable = false, length = 250)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "ruc", length = 13)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "coordenadasx", length = 250)
	public String getCoordenadasx() {
		return this.coordenadasx;
	}

	public void setCoordenadasx(String coordenadasx) {
		this.coordenadasx = coordenadasx;
	}

	@Column(name = "coordenadasy", length = 250)
	public String getCoordenadasy() {
		return this.coordenadasy;
	}

	public void setCoordenadasy(String coordenadasy) {
		this.coordenadasy = coordenadasy;
	}

	@Column(name = "direccion", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_apertura", length = 8)
	public Date getHoraApertura() {
		return this.horaApertura;
	}

	public void setHoraApertura(Date horaApertura) {
		this.horaApertura = horaApertura;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_cierre", length = 8)
	public Date getHoraCierre() {
		return this.horaCierre;
	}

	public void setHoraCierre(Date horaCierre) {
		this.horaCierre = horaCierre;
	}

	@Column(name = "ciudad", length = 45)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "costo_hora", precision = 10)
	public BigDecimal getCostoHora() {
		return this.costoHora;
	}

	public void setCostoHora(BigDecimal costoHora) {
		this.costoHora = costoHora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "complejo")
	public Set<Canchas> getCanchases() {
		return this.canchases;
	}

	public void setCanchases(Set<Canchas> canchases) {
		this.canchases = canchases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "complejo")
	public Set<Telefonos> getTelefonoses() {
		return this.telefonoses;
	}

	public void setTelefonoses(Set<Telefonos> telefonoses) {
		this.telefonoses = telefonoses;
	}

}
