package ec.edu.ups.canchas.objetos;
// Generated 09-feb-2016 21:36:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefonos generated by hbm2java
 */
@Entity
@Table(name = "telefonos", catalog = "canchas")
public class Telefonos implements java.io.Serializable {

	private int idtelefonos;
	private Complejo complejo;
	private String tipo;
	private String telefono;

	public Telefonos() {
	}

	public Telefonos(int idtelefonos, Complejo complejo) {
		this.idtelefonos = idtelefonos;
		this.complejo = complejo;
	}

	public Telefonos(int idtelefonos, Complejo complejo, String tipo, String telefono) {
		this.idtelefonos = idtelefonos;
		this.complejo = complejo;
		this.tipo = tipo;
		this.telefono = telefono;
	}

	@Id

	@Column(name = "idtelefonos", unique = true, nullable = false)
	public int getIdtelefonos() {
		return this.idtelefonos;
	}

	public void setIdtelefonos(int idtelefonos) {
		this.idtelefonos = idtelefonos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "complejo_idcomplejo", nullable = false)
	public Complejo getComplejo() {
		return this.complejo;
	}

	public void setComplejo(Complejo complejo) {
		this.complejo = complejo;
	}

	@Column(name = "tipo", length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "telefono", length = 150)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
